[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch", "xml2js", "vader-sentiment"]

[[redirects]]
  from = "/api/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
