# csp_project/project/netlify.toml
[build]
  base = "csp_project/project"
  command = "npm run build"
  commandOrigin = "config"
  publish = "dist"
  publishOrigin = "config"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/api/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
  redirectsOrigin = "config"
