[build]
  base = "csp_project/project"  # Relative path from repo root
  command = "npm run build"
  commandOrigin = "config"
  environment = [
    "NEWSAPI_API_KEY",
    "VITE_CRYPTOPANIC_API_TOKEN",
    "VITE_HUGGINGFACE_API_KEY",
    "VITE_OPENAI_API_KEY",
    "VITE_SANTIMENT_API_KEY",
    "COINMETRICS_API_KEY"  # Added for completeness
  ]
  publish = "dist"  # Relative to base directory
  publishOrigin = "config"

[functions]
  directory = "netlify/functions"  # Relative to repo root

[[redirects]]
  from = "/api/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
  redirectsOrigin = "config"
